### PR TITLE
Adding conduit, the matrix homeserver

### LINKED ISSUE #16: Add matrix homeserver
Note: I will try and work on this myself, since the docker-compose file for use with existing traefik is also provided.

### PR DESCRIPTION
**Pull request by kubo6472**
Closes #16

### CODE REVIEW

**Comment by kubo6472** [comment]
This needs heavy testing. I am still lost on how exactly this provides the files to the base domain, but we'll see :D

**Comment by sethforprivacy** [comment]
Will test and review when I have a bit more time, thanks for the contribution!

**Comment by jbakosi** [comment]
This does the trick for me:
```
+  conduit:
+    image: matrixconduit/matrix-conduit:latest
+    restart: unless-stopped
+    volumes:
+      - conduit-data:/var/lib/matrix-conduit/
+    environment:
+      CONDUIT_SERVER_NAME: ${CONDUIT_HOSTNAME}
+      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
+      CONDUIT_DATABASE_BACKEND: rocksdb
+      CONDUIT_PORT: 6167
+      CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
+      CONDUIT_ALLOW_REGISTRATION: 'true'
+      CONDUIT_ALLOW_FEDERATION: 'true'
+      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
+      CONDUIT_ADDRESS: 0.0.0.0
+      CONDUIT_CONFIG: ''
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.conduit.rule=Host(`${CONDUIT_HOSTNAME}`)"
+      - "traefik.http.routers.conduit.tls=true"
+      - "traefik.http.routers.conduit.tls.certresolver=selfhostedservices"
+      - "traefik.http.routers.conduit.middlewares=cors-headers@docker"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
+
+  well-known:
+    image: nginx:latest
+    restart: unless-stopped
+    volumes:
+      - ./conduit/wellknown.conf:/etc/nginx/conf.d/matrix.conf
+      - ./conduit/servnclient:/var/www/
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.wellknown.rule=Host(`${CONDUIT_HOSTNAME}`) && PathPrefix(`/.well-known/matrix`)"
+      - "traefik.http.routers.wellknown.tls=true"
+      - "traefik.http.routers.wellknown.tls.certresolver=selfhostedservices"
+      - "traefik.http.routers.wellknown.middlewares=cors-headers@docker"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
+      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
```
Test:
```
$ curl https://matrix.bakosi.org/_matrix/client/versions
{"versions":["r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.e2e_cross_signing":true}}
```

**Comment by sethforprivacy** [comment]
> This does the trick for me:
> 
> ```
> +  conduit:
> +    image: matrixconduit/matrix-conduit:latest
> +    restart: unless-stopped
> +    volumes:
> +      - conduit-data:/var/lib/matrix-conduit/
> +    environment:
> +      CONDUIT_SERVER_NAME: ${CONDUIT_HOSTNAME}
> +      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
> +      CONDUIT_DATABASE_BACKEND: rocksdb
> +      CONDUIT_PORT: 6167
> +      CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
> +      CONDUIT_ALLOW_REGISTRATION: 'true'
> +      CONDUIT_ALLOW_FEDERATION: 'true'
> +      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
> +      CONDUIT_ADDRESS: 0.0.0.0
> +      CONDUIT_CONFIG: ''
> +    labels:
> +      - "traefik.enable=true"
> +      - "traefik.http.routers.conduit.rule=Host(`${CONDUIT_HOSTNAME}`)"
> +      - "traefik.http.routers.conduit.tls=true"
> +      - "traefik.http.routers.conduit.tls.certresolver=selfhostedservices"
> +      - "traefik.http.routers.conduit.middlewares=cors-headers@docker"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
> +
> +  well-known:
> +    image: nginx:latest
> +    restart: unless-stopped
> +    volumes:
> +      - ./conduit/wellknown.conf:/etc/nginx/conf.d/matrix.conf
> +      - ./conduit/servnclient:/var/www/
> +    labels:
> +      - "traefik.enable=true"
> +      - "traefik.http.routers.wellknown.rule=Host(`${CONDUIT_HOSTNAME}`) && PathPrefix(`/.well-known/matrix`)"
> +      - "traefik.http.routers.wellknown.tls=true"
> +      - "traefik.http.routers.wellknown.tls.certresolver=selfhostedservices"
> +      - "traefik.http.routers.wellknown.middlewares=cors-headers@docker"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
> +      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
> ```
> 
> Test:
> 
> ```
> $ curl https://matrix.bakosi.org/_matrix/client/versions
> {"versions":["r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.e2e_cross_signing":true}}
> ```

Thoughts on these changes, @kubo6472? I haven't been able to test this out yet, but would love feedback on what @jbakosi ended up with 😃

**Comment by kubo6472** [comment]
Once I'll have some time, I will test it.

**Comment by kubo6472** [comment]
Yep, works

**Comment by jbakosi** [comment]
Also need to:
* fill out `<SUBDOMAIN>.<DOMAIN>` in `wellknown.conf`, and
* add `add_header "Access-Control-Allow-Origin" *;` under `location /.well-known/matrix/server`

Otherwise https://federationtester.matrix.org returns errors.

After that, federation still does _not_ work for me. When I try to explore public rooms, e.g., log into your matrix server as admin, then try to explore public rooms using another server, e.g., matrix.org, I get
```
$ docker-compose logs --follow conduit
conduit_1         | Mar 23 22:55:24.697  WARN conduit::server_server: https://matrix-federation.matrix.org/_matrix/federation/v1/publicRooms 401 Unauthorized: {"errcode":"M_UNAUTHORIZED","error":"Failed to find any key to satisfy: _FetchKeyRequest(server_name='matrix.bakosi.org', minimum_valid_until_ts=1648076124677, key_ids=['ed25519:Le6rhOZ2'])"}
```

**Comment by kubo6472** [comment]
I've since noticed another two issues. Await a fix in a few hours' time

**Comment by kubo6472** [comment]
I fixed both the federation and the root domain stuff. It is very bodgy, but it seems to work
image

**Comment by jbakosi** [comment]
Hey @kubo6472! Thanks for the fix but I am not finding your fix on the federation. Can you point me to it? Is it supposed to be be showing up on this PR's diff?

**Comment by kubo6472** [comment]
I bodged the rest of the compose a lot. Haven't send the commit out, yet.

**Comment by kubo6472** [comment]
Sorry, wanted to squash all of those commits but I messed it up 😄

**Comment by kubo6472** [comment]
@jbakosi not sure if I can explain. I just ran it and it worked. Make sure ti have both 443 and 80 opened.

**Comment by jbakosi** [comment]
Oh, weird! It now works for me too. Oh well... ;-)

**Comment by kubo6472** [comment]
> Oh, weird! It now works for me too. Oh well... ;-)

Glad to hear that.

**Comment by kubo6472** [comment]
@sethforprivacy I will write some guides for this, since it is a bit advanced to setup depending on if the user is okay with using a subdomain in their matrix handle, or giving up their primary domain for this, or having to mess with redirects, but other than that, I think we're looking at everything I set myself out to do.

**Comment by kubo6472** [comment]
Running this in production now. Are there bridges for signal, messenger and insta wanted, too? Can add them now. The docs are hell, I was figuring it out for 5 days straight. Got it working all yesterday.

**Comment by sethforprivacy** [comment]
I haven't messed with bridges at all at this point, as the only one I rely on is the IRC one run by Matrix themselves. There are very few reasons to self-host bridges IMO, so not a good thing to add into this setup IMO.

**Comment by jbakosi** [comment]
Isn't it only possible to use a matrix client, e.g., element, to send, say, telegram messages is to use a matrix bridge? And a bridge can only be configured on your own matrix server (or you can pay a monthly fee for it). For me setting up a telegram and maybe a signal bridge would be one of the main reasons to self-host a matrix server.

**Comment by sethforprivacy** [comment]
@jbakosi If you want, please either post an XMR (Monero) address here or DM me via any of these methods, would love to send you a tip for your work on this!

https://sethforprivacy.com/about/#how-to-contact-me

**Comment by jbakosi** [comment]
I do greatly appreciate the gesture, but I cannot accept that. Just following your work has helped me tremendously already.

**Comment by sethforprivacy** [comment]
Well then, keep up the good work and thank you so much for the help with this!

**Comment by kubo6472** [comment]
> That's quite a bit outside the scope of this repo, so I'd prefer to keep bridges out of this as it's going to be very subjective, and most people wanting to run a Matrix homeserver will be doing it to use Matrix, not another protocol.
> 
> You're more than welcome to keep up a fork with bridges added, though! Just want to keep this repo at least relatively streamlined and focused on tools that are more commonly used/needed.

I think when #2 will get implemented, it'll allow even for setups with bridges. Right now it's too "difficult" to turn off services. You can get into libera.chat without any third party software, at least with the element client, then you can keep your collection of bridges. With that you can have a stack that you own, with only relying on those external servers. I will make a PR probably sometime next week anyway. It can stay open, until there will be a mechanism to easily sellect services. I imagine with #2 a way to build out the initial docker-compose.yml file with only the services selected on "pull-time" but that's offtopic here. Thanks for the support and responses @jbakosi and for this project in the first place @sethforprivacy

**Pull request closed without merging**
